// rustc_codegen_js -- program
// Generated by `-Cllvm-args=js-dts=on`. Do not edit: it is rewritten on every build.

type CoreFmtArguments = { template: unknown; args: unknown };
type CoreMarkerPhantomDataStr = {};
type CoreOptionOptionF64 = { TAG: "None" } | { TAG: "Some"; 0: number };
type CorePanicLocation = { filename: unknown; line: number; col: number; _filename: CoreMarkerPhantomDataStr };
type CorePanicPanicInfo = { message: CoreFmtArguments; location: CorePanicLocation; can_unwind: boolean; force_no_backtrace: boolean };
type Direction = "North" | "South";
type JsValue = { readonly __JsValue: unique symbol };
type Node = { readonly __Node: unique symbol };
type Point = { x: number; y: number };
type Reply = { TAG: "Empty" } | { TAG: "Text"; 0: number } | { TAG: "Point"; x: number; y: number };
type Sig = { readonly __Sig: unique symbol };

declare module "chart.js" {
  export const ext$Chart$h63682570ca348144: unknown;
}

/** `fn(&core::panic::PanicInfo<'_>) -> !` */
export declare function _RNvCs1lVxXr9ZvqQ_7___rustc17rust_begin_unwind(_1: CorePanicPanicInfo): never;
/** `extern "C" fn(view_abi::Sig<f64>) -> view_abi::Sig<f64>` */
export declare function bump(count: Sig): Sig;
/** `extern "C" fn(view_abi::JsValue) -> view_abi::JsValue` */
export declare function chart(target: JsValue): JsValue;
/** `extern "C" fn(Reply) -> Reply` */
export declare function describe(reply: Reply): Reply;
/** `extern "C" fn(&str) -> &str` */
export declare function greet(name: string): string;
/** `extern "C" fn(f64, bool) -> core::option::Option<f64>` */
export declare function maybe(value: number, present: boolean): CoreOptionOptionF64;
/** `extern "C" fn(u32, u64, f64, bool, char) -> i64` */
export declare function primitives(count: number, big: bigint, ratio: number, flag: boolean, letter: number): bigint;
/** `extern "C" fn(Level) -> Level` */
export declare function raise(level: number): number;
/** `extern "C" fn(Point, f64) -> Point` */
export declare function shift(point: Point, by: number): Point;
/** `extern "C" fn(f64) -> (f64, f64)` */
export declare function split(value: number): [number, number];
/** `extern "C" fn(Direction) -> Direction` */
export declare function turn(direction: Direction): Direction;
/** `extern "C" fn(f64) -> view_abi::Node` */
export declare function wrap(value: number): Node;
