// GENERATED FILE -- do not edit by hand.
//
// Generated by runtime/dom/gen-index.mjs from contract/fixtures/abi.json
// (dom-expressions 0.40.8, solid-js 1.9.14).
//
// This is the entry point of the vendored client runtime. It re-exports, from
// solid-js/web, exactly the 48 names that make up the dom-expressions
// client ABI, and from solid-js the 2 reactive name(s) the emitter needs
// that the ABI does not carry (see reactive-additions.mjs). check-exports.mjs
// asserts the built bundle's export list equals those two lists exactly.
//
// WHY solid-js/web AND NOT dom-expressions DIRECTLY
// -------------------------------------------------
// dom-expressions ships src/client.js with an unresolved import from the bare
// specifier "rxcore" -- the reactivity seam. It is not a runnable package. Every
// name in the ABI is present in solid-js/web's browser build, which is
// dom-expressions' client.js already bound to solid's reactive core. Bundling
// solid-js/web therefore yields the ABI and its reactivity in one artifact, and
// the rxcore seam needs no wiring on our side.
//
// The "browser" export condition selects solid-js/web/dist/web.js. Under node
// the same specifier would resolve to the SSR build, whose surface differs --
// build.mjs sets platform: "browser" so the right one is picked.

export {
  Aliases,
  Assets,
  ChildProperties,
  DOMElements,
  DelegatedEvents,
  Hydration,
  HydrationScript,
  NoHydration,
  Properties,
  RequestContext,
  SVGElements,
  SVGNamespace,
  addEventListener,
  assign,
  classList,
  className,
  clearDelegatedEvents,
  createComponent,
  delegateEvents,
  dynamicProperty,
  effect,
  generateHydrationScript,
  getAssets,
  getHydrationKey,
  getNextElement,
  getNextMarker,
  getNextMatch,
  getOwner,
  getPropAlias,
  getRequestEvent,
  hydrate,
  innerHTML,
  insert,
  memo,
  mergeProps,
  render,
  runHydrationEvents,
  setAttribute,
  setAttributeNS,
  setBoolAttribute,
  setProperty,
  setStyleProperty,
  spread,
  style,
  template,
  untrack,
  use,
  useAssets
} from "solid-js/web";

// Not part of the dom-expressions ABI. solid-js/web resolves to the same copy of
// solid's core that the bundler inlines for these, so a signal created here and
// an effect created by the ABI's `effect` share one reactive graph.
export {
  createSignal,
  runWithOwner
} from "solid-js";
