// EXTRACTED ARTIFACT -- do not edit by hand.
//
// Generated by contract/harness/extract-bootstrap.mjs from
// solid-js@1.9.14
// web/dist/server.js:621 generateHydrationScript().
//
// WHAT THIS IS
// ------------
// The bootstrap <script> solid emits into SSR'd HTML. It runs BEFORE any
// framework code loads, and its only job is to capture events that fire on
// server-rendered markup during the window between first paint and hydration,
// so they can be replayed once the component that owns them is alive.
//
// It installs a global `_$HY`:
//
//   {
//     events:    [],             // captured [element, event] pairs, replayed
//                                //   by runHydrationEvents()
//     completed: new WeakSet,    // elements already hydrated -- events on
//                                //   these are NOT captured (they have real
//                                //   listeners now)
//     r:         {},             // resource/resolved-data registry. INERT in
//                                //   this build: written by the streaming SSR
//                                //   path, read by resource hydration. An
//                                //   emitter that does no streaming leaves it
//                                //   empty, but the KEY MUST EXIST -- solid's
//                                //   client reads _$HY.r unconditionally.
//     fe() {}                    // "flush events" hook. A no-op stub here;
//                                //   the streaming path replaces it. Again,
//                                //   must exist as a callable.
//   }
//
// Note there is NO `done` field in the initial shape -- it is assigned later
// by the client runtime, not by this bootstrap.
//
// The capture listener walks up from the event target to the nearest ancestor
// carrying `data-hk`, crossing shadow boundaries via `.host`. That walk is
// why data-hk on template roots is load-bearing: it is the hydration owner
// lookup for replayed events.
//
// The trailing `<!--xs-->` marker terminates the script section for solid's
// streaming parser.
//
// BUILD NOTE
// ----------
// ${EVENTS} sits INSIDE the quotes the template already supplies, mirroring
// solid's own `["${eventNames.join('", "')}"]`. Substitute the event names
// joined with the three-character sequence `", "` -- do NOT quote them
// yourself. For click+input the substituted value is exactly:  click", "input
//
// QUIRK -- an empty event list does NOT produce `[]`. Because the quotes are
// part of the template, an empty join yields `[""]`: solid registers a
// document listener for the empty-string event name. Harmless, but it means
// "capture nothing" is not expressible through eventNames; omit the script.
//
// IMPORTANT -- solid's default is NOT the delegated-events set. solid defaults
// eventNames to ["click", "input"] (TWO events). The 22 events in
// fixtures/delegated-events.json are what dom-expressions DELEGATES at runtime,
// which is a different and larger set. Whoever emits this script chooses the
// list; capturing all 22 costs 22 document listeners during the pre-hydration
// window. See CONTRACT-DOM.md.

/** The bootstrap template. ${EVENTS} takes a pre-quoted, comma-joined list. */
export const BOOTSTRAP_TEMPLATE = "<script>window._$HY||(e=>{let t=e=>e&&e.hasAttribute&&(e.hasAttribute(\"data-hk\")?e:t(e.host&&e.host.nodeType?e.host:e.parentNode));[\"${EVENTS}\"].forEach((o=>document.addEventListener(o,(o=>{if(!e.events)return;let s=t(o.composedPath&&o.composedPath()[0]||o.target);s&&!e.completed.has(s)&&e.events.push([s,o])}))))})(_$HY={events:[],completed:new WeakSet,r:{},fe(){}});</script><!--xs-->";

/** The same, with a ${NONCE} slot for a CSP nonce attribute value. */
export const BOOTSTRAP_TEMPLATE_NONCE = "<script nonce=\"${NONCE}\">window._$HY||(e=>{let t=e=>e&&e.hasAttribute&&(e.hasAttribute(\"data-hk\")?e:t(e.host&&e.host.nodeType?e.host:e.parentNode));[\"${EVENTS}\"].forEach((o=>document.addEventListener(o,(o=>{if(!e.events)return;let s=t(o.composedPath&&o.composedPath()[0]||o.target);s&&!e.completed.has(s)&&e.events.push([s,o])}))))})(_$HY={events:[],completed:new WeakSet,r:{},fe(){}});</script><!--xs-->";

/** The 22 delegated events, joined for substitution into ${EVENTS}. */
export const DELEGATED_EVENTS_LIST = "beforeinput\", \"click\", \"contextmenu\", \"dblclick\", \"focusin\", \"focusout\", \"input\", \"keydown\", \"keyup\", \"mousedown\", \"mousemove\", \"mouseout\", \"mouseover\", \"mouseup\", \"pointerdown\", \"pointermove\", \"pointerout\", \"pointerover\", \"pointerup\", \"touchend\", \"touchmove\", \"touchstart";

/** solid's own default event list, joined for substitution into ${EVENTS}. */
export const SOLID_DEFAULT_EVENTS_LIST = "click\", \"input";

/**
 * Build the bootstrap script for an event list.
 *
 * @param {string[]} eventNames events to capture before hydration
 * @param {string} [nonce] CSP nonce for the <script> tag
 * @returns {string} the full <script>...</script><!--xs--> string
 */
export function buildHydrationScript(eventNames, nonce) {
  const list = eventNames.join('", "');
  return nonce === undefined
    ? BOOTSTRAP_TEMPLATE.replace("${EVENTS}", list)
    : BOOTSTRAP_TEMPLATE_NONCE.replace("${EVENTS}", list).replace("${NONCE}", nonce);
}
