// Generate src/index.js from contract/fixtures/abi.json.
//
//   node gen-index.mjs
//
// The re-export list is DERIVED, never hand-maintained: if the ABI fixture
// changes because upstream changed, regenerating produces a diff instead of a
// silent mismatch between what the emitter calls and what the bundle exports.
//
// The ABI block comes from abi.json. The reactive block comes from
// reactive-additions.mjs, which carries the names the emitter needs that
// upstream's client.js does not export.

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { reactiveAdditions } from "./reactive-additions.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const abiPath = path.resolve(here, "..", "..", "contract", "fixtures", "abi.json");
const abi = JSON.parse(readFileSync(abiPath, "utf8"));

const names = abi.exports.map((e) => e.name).sort();
const missing = abi.solidWebParity.missingFromSolidWeb ?? [];
if (missing.length) {
  throw new Error(
    `abi.json reports names absent from solid-js/web: ${missing.join(", ")}. ` +
      `They cannot be re-exported and need an explicit alias -- see README.md.`
  );
}

const additions = Object.keys(reactiveAdditions).sort();
const duplicated = additions.filter((n) => names.includes(n));
if (duplicated.length) {
  throw new Error(
    `reactive-additions.mjs re-exports names the ABI already provides: ` +
      `${duplicated.join(", ")}. Exporting a name twice does not build.`
  );
}
const reactiveBlock = additions
  .map((n) => (reactiveAdditions[n] === n ? `  ${n}` : `  ${reactiveAdditions[n]} as ${n}`))
  .join(",\n");

const source = `// GENERATED FILE -- do not edit by hand.
//
// Generated by runtime/dom/gen-index.mjs from contract/fixtures/abi.json
// (dom-expressions ${abi.$extractedFrom["dom-expressions"]}, solid-js ${abi.$extractedFrom["solid-js"]}).
//
// This is the entry point of the vendored client runtime. It re-exports, from
// solid-js/web, exactly the ${names.length} names that make up the dom-expressions
// client ABI, and from solid-js the ${additions.length} reactive name(s) the emitter needs
// that the ABI does not carry (see reactive-additions.mjs). check-exports.mjs
// asserts the built bundle's export list equals those two lists exactly.
//
// WHY solid-js/web AND NOT dom-expressions DIRECTLY
// -------------------------------------------------
// dom-expressions ships src/client.js with an unresolved import from the bare
// specifier "rxcore" -- the reactivity seam. It is not a runnable package. Every
// name in the ABI is present in solid-js/web's browser build, which is
// dom-expressions' client.js already bound to solid's reactive core. Bundling
// solid-js/web therefore yields the ABI and its reactivity in one artifact, and
// the rxcore seam needs no wiring on our side.
//
// The "browser" export condition selects solid-js/web/dist/web.js. Under node
// the same specifier would resolve to the SSR build, whose surface differs --
// build.mjs sets platform: "browser" so the right one is picked.

export {
${names.map((n) => `  ${n}`).join(",\n")}
} from "solid-js/web";

// Not part of the dom-expressions ABI. solid-js/web resolves to the same copy of
// solid's core that the bundler inlines for these, so a signal created here and
// an effect created by the ABI's \`effect\` share one reactive graph.
export {
${reactiveBlock}
} from "solid-js";
`;

const dest = path.join(here, "src", "index.js");
writeFileSync(dest, source);
console.log(
  `src/index.js  ${names.length} ABI re-exports from abi.json ` +
    `+ ${additions.length} reactive addition(s): ${additions.join(", ")}`
);
