// SCAFFOLD: generated by dts.mjs and not yet reviewed.
// Delete the line above once this file asserts something about 01_shapes's API
// beyond the fact that it resolves. See the header of dts.mjs.

import type * as Island from "../emitted/01_shapes";

declare const _value__RNvCs1lVxXr9ZvqQ_7___rustc17rust_begin_unwind: typeof Island._RNvCs1lVxXr9ZvqQ_7___rustc17rust_begin_unwind;
void _value__RNvCs1lVxXr9ZvqQ_7___rustc17rust_begin_unwind;
declare const _value_bump: typeof Island.bump;
void _value_bump;
declare const _value_chart: typeof Island.chart;
void _value_chart;
declare const _value_describe: typeof Island.describe;
void _value_describe;
declare const _value_greet: typeof Island.greet;
void _value_greet;
declare const _value_maybe: typeof Island.maybe;
void _value_maybe;
declare const _value_primitives: typeof Island.primitives;
void _value_primitives;
declare const _value_raise: typeof Island.raise;
void _value_raise;
declare const _value_shift: typeof Island.shift;
void _value_shift;
declare const _value_split: typeof Island.split;
void _value_split;
declare const _value_turn: typeof Island.turn;
void _value_turn;
declare const _value_wrap: typeof Island.wrap;
void _value_wrap;
