// SCAFFOLD: generated by dts.mjs and not yet reviewed.
// Delete the line above once this file asserts something about 17_signal's API
// beyond the fact that it resolves. See the header of dts.mjs.

import type * as Island from "../emitted/17_signal";

declare const _value__RNvCs1lVxXr9ZvqQ_7___rustc17rust_begin_unwind: typeof Island._RNvCs1lVxXr9ZvqQ_7___rustc17rust_begin_unwind;
void _value__RNvCs1lVxXr9ZvqQ_7___rustc17rust_begin_unwind;
declare const _value_rust_entry: typeof Island.rust_entry;
void _value_rust_entry;
