// Regenerate every derived artifact in fixtures/corpus/.
//
//   node --import ./register-loader.mjs gen-corpus.mjs
//   node --import ./register-loader.mjs gen-corpus.mjs --only 03
//
// WHAT THE CORPUS IS
// ------------------
// One directory per construct family. Each holds a HAND-WRITTEN pair --
//
//   view.rs   the Topcoat view!-syntax fixture (the future input to OUR compiler)
//   jsx.jsx   the semantically equivalent JSX (input to the REFERENCE compiler)
//   NOTES.md  why they are equivalent and where they deliberately are not
//
// -- and three GENERATED artifacts this script produces from jsx.jsx:
//
//   expected.reference.js             compiled with PRESETS.dom
//   expected.reference.hydratable.js  compiled with PRESETS.domHydratable
//   expected.reference.trace          the dom output run against the stub
//
// Nothing here is transcribed by hand. A diff in a generated file after a
// version bump is the drift report, same rule as the rest of fixtures/.
//
// WHY THE TRACE RUNS IN A SUBPROCESS
// ----------------------------------
// trace.mjs's `__reset()` deliberately does NOT reset its hydration counter,
// and run-trace.mjs heals missing free identifiers by assigning to globalThis.
// Both are process-global, so tracing seventeen fixtures in one process would
// make each fixture's trace depend on the ones before it. A fresh subprocess per
// fixture makes each trace independent of corpus ordering. It also means this
// script cannot perturb the committed reference-traces/, which are recorded by
// run-trace.mjs --record in its own process.

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import path from "node:path";
import { HARNESS, FIXTURES, provenance } from "./paths.mjs";
import { compile, PRESETS } from "./compile-reference.mjs";

export const CORPUS = path.join(FIXTURES, "corpus");

/** Every corpus family directory, in name order (which is the numbered order). */
export function families() {
  return readdirSync(CORPUS, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort();
}

const argv = process.argv.slice(2);
const onlyIdx = argv.indexOf("--only");
const only = onlyIdx >= 0 ? argv[onlyIdx + 1] : null;

/**
 * The banner every generated file carries. Written as JS line comments so the
 * file is still executable -- run-trace.mjs imports expected.reference.js as-is.
 */
function banner(family, preset) {
  const p = provenance("gen-corpus.mjs");
  return [
    `// GENERATED by ${p.$generatedBy} -- DO NOT EDIT BY HAND.`,
    `// ${p.$doNotEditByHand}`,
    `//`,
    `// family:  ${family}`,
    `// source:  fixtures/corpus/${family}/jsx.jsx`,
    `// preset:  ${preset} (see harness/compile-reference.mjs PRESETS)`,
    `// plugin:  babel-plugin-jsx-dom-expressions@${p.$extractedFrom["babel-plugin-jsx-dom-expressions"]}`,
    `// gitSha:  ${p.$extractedFrom.gitSha}`,
    ""
  ].join("\n");
}

/**
 * Run one compiled module against the recording stub, in its own process.
 * Returns the trace as JSON Lines with our own header line substituted in, or
 * null when the subprocess itself failed (as opposed to the traced module
 * throwing, which run-trace.mjs reports in-band as status: "stopped-early").
 */
function traceInSubprocess(jsPath, family) {
  let stdout;
  try {
    stdout = execFileSync(
      process.execPath,
      [
        "--import",
        path.join(HARNESS, "register-loader.mjs"),
        path.join(HARNESS, "run-trace.mjs"),
        "--file",
        jsPath
      ],
      { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"], cwd: HARNESS }
    );
  } catch (err) {
    return { jsonl: null, header: null, error: `run-trace exited ${err.status}` };
  }

  const lines = stdout.split("\n").filter(Boolean);
  if (!lines.length) return { jsonl: null, header: null, error: "run-trace produced no output" };

  // run-trace.mjs's --file header carries only label/status/healed. Replace it
  // with the same header --record writes, so a corpus trace and a reference
  // trace are the same kind of document.
  const raw = JSON.parse(lines[0]);
  const header = {
    $record: "header",
    ...provenance("gen-corpus.mjs"),
    $what:
      "Normalized runtime-call trace of a reference-compiled CORPUS fixture executed " +
      "against harness/trace.mjs. Node identities are renamed in first-appearance " +
      "order; functions become fn#N; templates become tmpl#N.",
    fixture: `corpus/${family}`,
    label: `corpus/${family}`,
    freeBindingsHealed: raw.freeBindingsHealed,
    status: raw.status,
    error: raw.error,
    recordCount: raw.recordCount
  };

  return {
    jsonl: `${[JSON.stringify(header), ...lines.slice(1)].join("\n")}\n`,
    header,
    error: null
  };
}

// ------------------------------------------------------------------- run
const summary = [];

for (const family of families()) {
  if (only && !family.startsWith(only)) continue;

  const dir = path.join(CORPUS, family);
  const jsxPath = path.join(dir, "jsx.jsx");
  if (!existsSync(jsxPath)) {
    summary.push({ family, dom: "MISSING jsx.jsx", hydratable: "-", trace: "-" });
    continue;
  }
  const source = readFileSync(jsxPath, "utf8");

  const row = { family, dom: null, hydratable: null, trace: null, records: 0 };

  // --- dom (hydratable: false)
  const domPath = path.join(dir, "expected.reference.js");
  try {
    const code = compile(source, { filename: jsxPath, cwd: dir, ...PRESETS.dom });
    writeFileSync(domPath, banner(family, "dom") + code);
    row.dom = "ok";
  } catch (err) {
    row.dom = `FAILED: ${err.message.split("\n")[0]}`;
  }

  // --- dom (hydratable: true)
  try {
    const code = compile(source, { filename: jsxPath, cwd: dir, ...PRESETS.domHydratable });
    writeFileSync(
      path.join(dir, "expected.reference.hydratable.js"),
      banner(family, "domHydratable") + code
    );
    row.hydratable = "ok";
  } catch (err) {
    row.hydratable = `FAILED: ${err.message.split("\n")[0]}`;
  }

  // --- trace, over the non-hydratable output
  if (row.dom === "ok") {
    const { jsonl, header, error } = traceInSubprocess(domPath, family);
    if (jsonl) {
      writeFileSync(path.join(dir, "expected.reference.trace"), jsonl);
      row.trace = header.status;
      row.records = header.recordCount;
      row.healed = header.freeBindingsHealed;
    } else {
      row.trace = `SKIPPED: ${error}`;
    }
  } else {
    row.trace = "SKIPPED: no dom output";
  }

  summary.push(row);
}

// ------------------------------------------------------------------- report
const pad = (s, n) => String(s).padEnd(n);
console.log(
  `${pad("family", 24)} ${pad("dom", 8)} ${pad("hydratable", 12)} ${pad("trace", 16)} records`
);
for (const r of summary) {
  console.log(
    `${pad(r.family, 24)} ${pad(r.dom, 8)} ${pad(r.hydratable, 12)} ${pad(r.trace, 16)} ${r.records ?? ""}`
  );
}

const failed = summary.filter((r) => String(r.dom).startsWith("FAILED")).length;
const completed = summary.filter((r) => r.trace === "completed").length;
console.log(
  `\ncorpus: ${summary.length} families, ${summary.length - failed} compiled, ` +
    `${completed} traced to completion`
);
if (failed) process.exitCode = 1;
