// rustc_codegen_js -- program
// Generated by `-Cllvm-args=js-dts=on`. Do not edit: it is rewritten on every build.

type CoreFmtArguments = { template: unknown; args: unknown };
type CoreMarkerPhantomDataStr = {  };
type CorePanicLocation = { filename: unknown; line: number; col: number; _filename: CoreMarkerPhantomDataStr };
type CorePanicPanicInfo = { message: CoreFmtArguments; location: CorePanicLocation; can_unwind: boolean; force_no_backtrace: boolean };

declare module "./topcoat-dom.js" {
  export const _$createSignal: unknown;
  export const _$delegateEvents: unknown;
  export const _$effect: unknown;
  export const _$insert: unknown;
  export const _$template: unknown;
}

/** `fn(&core::panic::PanicInfo<'_>) -> !` */
export declare function _RNvCs1lVxXr9ZvqQ_7___rustc17rust_begin_unwind(_1: CorePanicPanicInfo): never;
/** `fn()` */
export declare function rust_entry(): void;
